# Generated by Django 4.2.5 on 2023-09-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_member_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.CharField(max_length=10)),
                ('payment_status', models.CharField(blank=True, max_length=10, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_payment', to='web.member')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
